# Generated by Django 4.0.5 on 2022-06-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Slug',
            new_name='slug',
        ),
    ]
